### ISSUE TITLE
json & yaml based models

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#129]
## Motivation

Currently, developers are able to create models via TypeScript classes. On the other hand, our models are very declarative except for the `serialization()` function. After [#125](https://github.com/axe-api/axe-api/issues/125), we should be able to use json-based or yaml-based models. 

This is important because after we do this, it means we can keep the models on any data source like a database server. Also, it means that we will be able to manage our models via GUI. 

### Configuration

Developers should be able to select one of the different kinds of resolvers. But in a project, there should be only one resolver can be used. It should be configurable.

### Convertible

Developers should be able to convert from one model declaration system to another. Axe API should provide some kind of tool that can be used via CLI.

### Unified Model Interface (UMI)

Whatever the developer use as the model declaration method, it should be kept in the memory as the same model structure. We should call that structure a `Unified Model Interface` (UMI).

### Documentation

Developers should be able to see all of the examples in different formats on the documentation because we provide multiple formats at the same time.

## JSON

This is a simple example of the `User.json` model.

```json
{
  "primaryKey": "id",
  "table": "users",
  "fillable": {
    "POST": ["name", "surname", "email"],
    "PUT": ["name", "surname", "email"]
  },
  "validations": {
    "POST": {
      "name": "required",
      "surname": "required",
      "email": "required|email",
    },
    "PUT": {
      "name": "required",
      "surname": "required",
      "email": "required|email",
    },
  },
  "handlers": ["PAGINATION", "INSERT"],
  "middlewares": ["isLogged", "isAdmin"],
  "hiddens": ["password_hash"],
  "createdAtColumn": "created_at",
  "updatedAtColumn": "updated_at",
  "transaction": [
    {
      "handler": "INSERT",
      "transaction": true,
    }
  ],
  "ignore": false
}
```

## Yaml

This is a simple example of `User.yaml` model;

```yaml
---
---
primaryKey: id
table: users
fillable:
  POST:
    - name
    - surname
    - email
  PUT:
    - name
    - surname
    - email
validations:
  POST:
    name: required
    surname: required
    email: required|email
  PUT:
    name: required
    surname: required
    email: required|email
handlers:
  - PAGINATION
  - INSERT
middlewares:
  - isLogged
  - isAdmin
hiddens:
  - password_hash
createdAtColumn: created_at
updatedAtColumn: updated_at
transaction:
  - handler: INSERT
    transaction: true
ignore: false
```
