### ISSUE TITLE
Auto docs - Deprecated Feature

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#138]
The details will be provided soon. Currently, we are working on it. 

### Deprecated Feature

Developers should be able to decide to mark some as `deprecated` some features;

- Endpoints: `/api/v1/users/:id`
- Fields: `users.full_name`
- Validation: `users.name:required`
- Middlewares: `isAdmin` (Somehow)
- Supported language: `en`

To define these kinds of deprecated values, developers should be able to manage some kind of configuration file like the following one;

`docs/deprecation.yml`
```yaml
- version: v1
  endpoints:
    - User.paginate
    - User.show
    - User.store
  fields:
    - User.full_name
    - User.gender
    - User.age
  validations:
    - User:POST:email:required
    - User:PUT:email:required
    - Post.phone:number
  middlewares:
    - isAdmin
    - Posts.shouldBeModerator
  supportedLanguages:
    - en
    - en-GB
    - en-UK
- version: v2
  endpoints:
    - Metric.*
```

> This is related to [Auto docs creation](https://github.com/axe-api/axe-api/issues/138). Actually, developers don't have to do anything in the code.
